recipe/meta.yaml

Update jupyter-sysml-kernel to 2021-04

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 2021-03a

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 2021-05

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 2021-05a

---

recipe/meta.yaml

Update openjdk to 11

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.14.1

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.15.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.15.1

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.15.2

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.17.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.18.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.19.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.20.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.22.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.22.1

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.23.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.24.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.25.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.26.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.27.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.28.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.28.1

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.29.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.30.0

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.31.0

---

recipe/meta.yaml

Update jupyter-sysml-kerml to 0.33.0.

---

recipe/meta.yaml

Update jupyter-sysml-kerml to 0.34.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.35.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.36.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.37.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.38.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.39.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.40.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.41.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.41.1.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.42.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.43.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.43.2.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.44.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.45.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.46.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.47.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.48.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.49.0.

---

recipe/meta.yaml

Update jupyter-sysml-kernel to 0.50.0.
